{*
* 2007-2018 ETS-Soft
*
* NOTICE OF LICENSE
*
* This file is not open source! Each license that you purchased is only available for 1 wesite only.
* If you want to use this file on more websites (or projects), you need to purchase additional licenses.
* You are not allowed to redistribute, resell, lease, license, sub-license or offer our resources to any third party.
*
* DISCLAIMER
*
* Do not edit or add to this file if you wish to upgrade PrestaShop to newer
* versions in the future. If you wish to customize PrestaShop for your
* needs, please contact us for extra customization service at an affordable price
*
*  @author ETS-Soft <etssoft.jsc@gmail.com>
*  @copyright  2007-2018 ETS-Soft
*  @license    Valid for 1 website (or project) for each purchase of license
*  International Registered Trademark & Property of ETS-Soft
*}
<div class="mm_close">{l s='Close' mod='ets_megamenu'}</div>
<div class="mm_form">
    <div class="defaultForm">
        <div class="panel">
            <div class="panel-heading">{l s='Browse icon' mod='ets_megamenu'}</div>
            <div id="awesome-icon" class="mm-tab-icon-content">
                <div class="mm_icon" data-icon="fa-address-book"><i class="fa fa-address-book" aria-hidden="true"></i> address-book</div>
                <div class="mm_icon" data-icon="fa-address-book-o"><i class="fa fa-address-book-o" aria-hidden="true"></i> address-book-o</div>
                <div class="mm_icon" data-icon="fa-address-card"><i class="fa fa-address-card" aria-hidden="true"></i> address-card</div>
                <div class="mm_icon" data-icon="fa-address-card-o"><i class="fa fa-address-card-o" aria-hidden="true"></i> address-card-o</div>
                <div class="mm_icon" data-icon="fa-adjust"><i class="fa fa-adjust" aria-hidden="true"></i> adjust</div>
                <div class="mm_icon" data-icon="fa-american-sign-language-interpreting"><i class="fa fa-american-sign-language-interpreting" aria-hidden="true"></i> american-sign-language-interpreting</div>
                <div class="mm_icon" data-icon="fa-anchor"><i class="fa fa-anchor" aria-hidden="true"></i> anchor</div>
                <div class="mm_icon" data-icon="fa-archive"><i class="fa fa-archive" aria-hidden="true"></i> archive</div>
                <div class="mm_icon" data-icon="fa-area-chart"><i class="fa fa-area-chart" aria-hidden="true"></i> area-chart</div>
                <div class="mm_icon" data-icon="fa-arrows"><i class="fa fa-arrows" aria-hidden="true"></i> arrows</div>
                <div class="mm_icon" data-icon="fa-arrows-h"><i class="fa fa-arrows-h" aria-hidden="true"></i> arrows-h</div>
                <div class="mm_icon" data-icon="fa-arrows-v"><i class="fa fa-arrows-v" aria-hidden="true"></i> arrows-v</div>
                <div class="mm_icon" data-icon="fa-assistive-listening-systems"><i class="fa fa-assistive-listening-systems" aria-hidden="true"></i> assistive-listening-systems</div>
                <div class="mm_icon" data-icon="fa-asterisk"><i class="fa fa-asterisk" aria-hidden="true"></i> asterisk</div>
                <div class="mm_icon" data-icon="fa-at"><i class="fa fa-at" aria-hidden="true"></i> at</div>
                <div class="mm_icon" data-icon="fa-audio-description"><i class="fa fa-audio-description" aria-hidden="true"></i> audio-description</div>
                <div class="mm_icon" data-icon="fa-balance-scale"><i class="fa fa-balance-scale" aria-hidden="true"></i> balance-scale</div>
                <div class="mm_icon" data-icon="fa-ban"><i class="fa fa-ban" aria-hidden="true"></i> ban</div>
                <div class="mm_icon" data-icon="fa-university"><i class="fa fa-bank" aria-hidden="true"></i> bank </div>
                <div class="mm_icon" data-icon="fa-bar-chart"><i class="fa fa-bar-chart" aria-hidden="true"></i> bar-chart</div>
                <div class="mm_icon" data-icon="fa-barcode"><i class="fa fa-barcode" aria-hidden="true"></i> barcode</div>
                <div class="mm_icon" data-icon="fa-bars"><i class="fa fa-bars" aria-hidden="true"></i> bars</div>
                <div class="mm_icon" data-icon="fa-bath"><i class="fa fa-bath" aria-hidden="true"></i> bath</div>
                <div class="mm_icon" data-icon="fa-bath"><i class="fa fa-bathtub" aria-hidden="true"></i> bathtub </div>
                <div class="mm_icon" data-icon="fa-battery-empty"><i class="fa fa-battery-empty" aria-hidden="true"></i> battery-empty</div>
                <div class="mm_icon" data-icon="fa-battery-full"><i class="fa fa-battery-full" aria-hidden="true"></i> battery-full</div>
                <div class="mm_icon" data-icon="fa-battery-half"><i class="fa fa-battery-half" aria-hidden="true"></i> battery-half</div>
                <div class="mm_icon" data-icon="fa-battery-quarter"><i class="fa fa-battery-quarter" aria-hidden="true"></i> battery-quarter</div>
                <div class="mm_icon" data-icon="fa-battery-three-quarters"><i class="fa fa-battery-three-quarters" aria-hidden="true"></i> battery-three-quarters</div>
                <div class="mm_icon" data-icon="fa-bed"><i class="fa fa-bed" aria-hidden="true"></i> bed</div>
                <div class="mm_icon" data-icon="fa-beer"><i class="fa fa-beer" aria-hidden="true"></i> beer</div>
                <div class="mm_icon" data-icon="fa-bell"><i class="fa fa-bell" aria-hidden="true"></i> bell</div>
                <div class="mm_icon" data-icon="fa-bell-o"><i class="fa fa-bell-o" aria-hidden="true"></i> bell-o</div>
                <div class="mm_icon" data-icon="fa-bell-slash"><i class="fa fa-bell-slash" aria-hidden="true"></i> bell-slash</div>
                <div class="mm_icon" data-icon="fa-bell-slash-o"><i class="fa fa-bell-slash-o" aria-hidden="true"></i> bell-slash-o</div>
                <div class="mm_icon" data-icon="fa-bicycle"><i class="fa fa-bicycle" aria-hidden="true"></i> bicycle</div>
                <div class="mm_icon" data-icon="fa-binoculars"><i class="fa fa-binoculars" aria-hidden="true"></i> binoculars</div>
                <div class="mm_icon" data-icon="fa-birthday-cake"><i class="fa fa-birthday-cake" aria-hidden="true"></i> birthday-cake</div>
                <div class="mm_icon" data-icon="fa-blind"><i class="fa fa-blind" aria-hidden="true"></i> blind</div>
                <div class="mm_icon" data-icon="fa-bluetooth"><i class="fa fa-bluetooth" aria-hidden="true"></i> bluetooth</div>
                <div class="mm_icon" data-icon="fa-bluetooth-b"><i class="fa fa-bluetooth-b" aria-hidden="true"></i> bluetooth-b</div>
                <div class="mm_icon" data-icon="fa-bolt"><i class="fa fa-bolt" aria-hidden="true"></i> bolt</div>
                <div class="mm_icon" data-icon="fa-bomb"><i class="fa fa-bomb" aria-hidden="true"></i> bomb</div>
                <div class="mm_icon" data-icon="fa-book"><i class="fa fa-book" aria-hidden="true"></i> book</div>
                <div class="mm_icon" data-icon="fa-bookmark"><i class="fa fa-bookmark" aria-hidden="true"></i> bookmark</div>
                <div class="mm_icon" data-icon="fa-bookmark-o"><i class="fa fa-bookmark-o" aria-hidden="true"></i> bookmark-o</div>
                <div class="mm_icon" data-icon="fa-braille"><i class="fa fa-braille" aria-hidden="true"></i> braille</div>
                <div class="mm_icon" data-icon="fa-briefcase"><i class="fa fa-briefcase" aria-hidden="true"></i> briefcase</div>
                <div class="mm_icon" data-icon="fa-bug"><i class="fa fa-bug" aria-hidden="true"></i> bug</div>
                <div class="mm_icon" data-icon="fa-building"><i class="fa fa-building" aria-hidden="true"></i> building</div>
                <div class="mm_icon" data-icon="fa-building-o"><i class="fa fa-building-o" aria-hidden="true"></i> building-o</div>
                <div class="mm_icon" data-icon="fa-bullhorn"><i class="fa fa-bullhorn" aria-hidden="true"></i> bullhorn</div>
                <div class="mm_icon" data-icon="fa-bullseye"><i class="fa fa-bullseye" aria-hidden="true"></i> bullseye</div>
                <div class="mm_icon" data-icon="fa-bus"><i class="fa fa-bus" aria-hidden="true"></i> bus</div>
                <div class="mm_icon" data-icon="fa-calculator"><i class="fa fa-calculator" aria-hidden="true"></i> calculator</div>
                <div class="mm_icon" data-icon="fa-calendar"><i class="fa fa-calendar" aria-hidden="true"></i> calendar</div>
                <div class="mm_icon" data-icon="fa-calendar-check-o"><i class="fa fa-calendar-check-o" aria-hidden="true"></i> calendar-check-o</div>
                <div class="mm_icon" data-icon="fa-calendar-minus-o"><i class="fa fa-calendar-minus-o" aria-hidden="true"></i> calendar-minus-o</div>
                <div class="mm_icon" data-icon="fa-calendar-o"><i class="fa fa-calendar-o" aria-hidden="true"></i> calendar-o</div>
                <div class="mm_icon" data-icon="fa-calendar-plus-o"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i> calendar-plus-o</div>
                <div class="mm_icon" data-icon="fa-calendar-times-o"><i class="fa fa-calendar-times-o" aria-hidden="true"></i> calendar-times-o</div>
                <div class="mm_icon" data-icon="fa-camera"><i class="fa fa-camera" aria-hidden="true"></i> camera</div>
                <div class="mm_icon" data-icon="fa-camera-retro"><i class="fa fa-camera-retro" aria-hidden="true"></i> camera-retro</div>
                <div class="mm_icon" data-icon="fa-car"><i class="fa fa-car" aria-hidden="true"></i> car</div>
                <div class="mm_icon" data-icon="fa-caret-square-o-down"><i class="fa fa-caret-square-o-down" aria-hidden="true"></i> caret-square-o-down</div>
                <div class="mm_icon" data-icon="fa-caret-square-o-left"><i class="fa fa-caret-square-o-left" aria-hidden="true"></i> caret-square-o-left</div>
                <div class="mm_icon" data-icon="fa-caret-square-o-right"><i class="fa fa-caret-square-o-right" aria-hidden="true"></i> caret-square-o-right</div>
                <div class="mm_icon" data-icon="fa-caret-square-o-up"><i class="fa fa-caret-square-o-up" aria-hidden="true"></i> caret-square-o-up</div>
                <div class="mm_icon" data-icon="fa-cart-arrow-down"><i class="fa fa-cart-arrow-down" aria-hidden="true"></i> cart-arrow-down</div>
                <div class="mm_icon" data-icon="fa-cart-plus"><i class="fa fa-cart-plus" aria-hidden="true"></i> cart-plus</div>
                <div class="mm_icon" data-icon="fa-cc"><i class="fa fa-cc" aria-hidden="true"></i> cc</div>
                <div class="mm_icon" data-icon="fa-certificate"><i class="fa fa-certificate" aria-hidden="true"></i> certificate</div>
                <div class="mm_icon" data-icon="fa-check"><i class="fa fa-check" aria-hidden="true"></i> check</div>
                <div class="mm_icon" data-icon="fa-check-circle"><i class="fa fa-check-circle" aria-hidden="true"></i> check-circle</div>
                <div class="mm_icon" data-icon="fa-check-circle-o"><i class="fa fa-check-circle-o" aria-hidden="true"></i> check-circle-o</div>
                <div class="mm_icon" data-icon="fa-check-square"><i class="fa fa-check-square" aria-hidden="true"></i> check-square</div>
                <div class="mm_icon" data-icon="fa-check-square-o"><i class="fa fa-check-square-o" aria-hidden="true"></i> check-square-o</div>
                <div class="mm_icon" data-icon="fa-child"><i class="fa fa-child" aria-hidden="true"></i> child</div>
                <div class="mm_icon" data-icon="fa-circle"><i class="fa fa-circle" aria-hidden="true"></i> circle</div>
                <div class="mm_icon" data-icon="fa-circle-o"><i class="fa fa-circle-o" aria-hidden="true"></i> circle-o</div>
                <div class="mm_icon" data-icon="fa-circle-o-notch"><i class="fa fa-circle-o-notch" aria-hidden="true"></i> circle-o-notch</div>
                <div class="mm_icon" data-icon="fa-circle-thin"><i class="fa fa-circle-thin" aria-hidden="true"></i> circle-thin</div>
                <div class="mm_icon" data-icon="fa-clock-o"><i class="fa fa-clock-o" aria-hidden="true"></i> clock-o</div>
                <div class="mm_icon" data-icon="fa-clone"><i class="fa fa-clone" aria-hidden="true"></i> clone</div>
                <div class="mm_icon" data-icon="fa-cloud"><i class="fa fa-cloud" aria-hidden="true"></i> cloud</div>
                <div class="mm_icon" data-icon="fa-cloud-download"><i class="fa fa-cloud-download" aria-hidden="true"></i> cloud-download</div>
                <div class="mm_icon" data-icon="fa-cloud-upload"><i class="fa fa-cloud-upload" aria-hidden="true"></i> cloud-upload</div>
                <div class="mm_icon" data-icon="fa-code"><i class="fa fa-code" aria-hidden="true"></i> code</div>
                <div class="mm_icon" data-icon="fa-code-fork"><i class="fa fa-code-fork" aria-hidden="true"></i> code-fork</div>
                <div class="mm_icon" data-icon="fa-coffee"><i class="fa fa-coffee" aria-hidden="true"></i> coffee</div>
                <div class="mm_icon" data-icon="fa-cog"><i class="fa fa-cog" aria-hidden="true"></i> cog</div>
                <div class="mm_icon" data-icon="fa-cogs"><i class="fa fa-cogs" aria-hidden="true"></i> cogs</div>
                <div class="mm_icon" data-icon="fa-comment"><i class="fa fa-comment" aria-hidden="true"></i> comment</div>
                <div class="mm_icon" data-icon="fa-comment-o"><i class="fa fa-comment-o" aria-hidden="true"></i> comment-o</div>
                <div class="mm_icon" data-icon="fa-commenting"><i class="fa fa-commenting" aria-hidden="true"></i> commenting</div>
                <div class="mm_icon" data-icon="fa-commenting-o"><i class="fa fa-commenting-o" aria-hidden="true"></i> commenting-o</div>
                <div class="mm_icon" data-icon="fa-comments"><i class="fa fa-comments" aria-hidden="true"></i> comments</div>
                <div class="mm_icon" data-icon="fa-comments-o"><i class="fa fa-comments-o" aria-hidden="true"></i> comments-o</div>
                <div class="mm_icon" data-icon="fa-compass"><i class="fa fa-compass" aria-hidden="true"></i> compass</div>
                <div class="mm_icon" data-icon="fa-copyright"><i class="fa fa-copyright" aria-hidden="true"></i> copyright</div>
                <div class="mm_icon" data-icon="fa-creative-commons"><i class="fa fa-creative-commons" aria-hidden="true"></i> creative-commons</div>
                <div class="mm_icon" data-icon="fa-credit-card"><i class="fa fa-credit-card" aria-hidden="true"></i> credit-card</div>
                <div class="mm_icon" data-icon="fa-credit-card-alt"><i class="fa fa-credit-card-alt" aria-hidden="true"></i> credit-card-alt</div>
                <div class="mm_icon" data-icon="fa-crop"><i class="fa fa-crop" aria-hidden="true"></i> crop</div>
                <div class="mm_icon" data-icon="fa-crosshairs"><i class="fa fa-crosshairs" aria-hidden="true"></i> crosshairs</div>
                <div class="mm_icon" data-icon="fa-cube"><i class="fa fa-cube" aria-hidden="true"></i> cube</div>
                <div class="mm_icon" data-icon="fa-cubes"><i class="fa fa-cubes" aria-hidden="true"></i> cubes</div>
                <div class="mm_icon" data-icon="fa-cutlery"><i class="fa fa-cutlery" aria-hidden="true"></i> cutlery</div>
                <div class="mm_icon" data-icon="fa-database"><i class="fa fa-database" aria-hidden="true"></i> database</div>
                <div class="mm_icon" data-icon="fa-deaf"><i class="fa fa-deaf" aria-hidden="true"></i> deaf</div>
                <div class="mm_icon" data-icon="fa-desktop"><i class="fa fa-desktop" aria-hidden="true"></i> desktop</div>
                <div class="mm_icon" data-icon="fa-diamond"><i class="fa fa-diamond" aria-hidden="true"></i> diamond</div>
                <div class="mm_icon" data-icon="fa-dot-circle-o"><i class="fa fa-dot-circle-o" aria-hidden="true"></i> dot-circle-o</div>
                <div class="mm_icon" data-icon="fa-download"><i class="fa fa-download" aria-hidden="true"></i> download</div>
                <div class="mm_icon" data-icon="fa-ellipsis-h"><i class="fa fa-ellipsis-h" aria-hidden="true"></i> ellipsis-h</div>
                <div class="mm_icon" data-icon="fa-ellipsis-v"><i class="fa fa-ellipsis-v" aria-hidden="true"></i> ellipsis-v</div>
                <div class="mm_icon" data-icon="fa-envelope"><i class="fa fa-envelope" aria-hidden="true"></i> envelope</div>
                <div class="mm_icon" data-icon="fa-envelope-o"><i class="fa fa-envelope-o" aria-hidden="true"></i> envelope-o</div>
                <div class="mm_icon" data-icon="fa-envelope-open"><i class="fa fa-envelope-open" aria-hidden="true"></i> envelope-open</div>
                <div class="mm_icon" data-icon="fa-envelope-open-o"><i class="fa fa-envelope-open-o" aria-hidden="true"></i> envelope-open-o</div>
                <div class="mm_icon" data-icon="fa-envelope-square"><i class="fa fa-envelope-square" aria-hidden="true"></i> envelope-square</div>
                <div class="mm_icon" data-icon="fa-eraser"><i class="fa fa-eraser" aria-hidden="true"></i> eraser</div>
                <div class="mm_icon" data-icon="fa-exchange"><i class="fa fa-exchange" aria-hidden="true"></i> exchange</div>
                <div class="mm_icon" data-icon="fa-exclamation"><i class="fa fa-exclamation" aria-hidden="true"></i> exclamation</div>
                <div class="mm_icon" data-icon="fa-exclamation-circle"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> exclamation-circle</div>
                <div class="mm_icon" data-icon="fa-exclamation-triangle"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> exclamation-triangle</div>
                <div class="mm_icon" data-icon="fa-external-link"><i class="fa fa-external-link" aria-hidden="true"></i> external-link</div>
                <div class="mm_icon" data-icon="fa-external-link-square"><i class="fa fa-external-link-square" aria-hidden="true"></i> external-link-square</div>
                <div class="mm_icon" data-icon="fa-eye"><i class="fa fa-eye" aria-hidden="true"></i> eye</div>
                <div class="mm_icon" data-icon="fa-eye-slash"><i class="fa fa-eye-slash" aria-hidden="true"></i> eye-slash</div>
                <div class="mm_icon" data-icon="fa-eyedropper"><i class="fa fa-eyedropper" aria-hidden="true"></i> eyedropper</div>
                <div class="mm_icon" data-icon="fa-fax"><i class="fa fa-fax" aria-hidden="true"></i> fax</div>
                <div class="mm_icon" data-icon="fa-female"><i class="fa fa-female" aria-hidden="true"></i> female</div>
                <div class="mm_icon" data-icon="fa-fighter-jet"><i class="fa fa-fighter-jet" aria-hidden="true"></i> fighter-jet</div>
                <div class="mm_icon" data-icon="fa-file-archive-o"><i class="fa fa-file-archive-o" aria-hidden="true"></i> file-archive-o</div>
                <div class="mm_icon" data-icon="fa-file-audio-o"><i class="fa fa-file-audio-o" aria-hidden="true"></i> file-audio-o</div>
                <div class="mm_icon" data-icon="fa-file-code-o"><i class="fa fa-file-code-o" aria-hidden="true"></i> file-code-o</div>
                <div class="mm_icon" data-icon="fa-file-excel-o"><i class="fa fa-file-excel-o" aria-hidden="true"></i> file-excel-o</div>
                <div class="mm_icon" data-icon="fa-file-image-o"><i class="fa fa-file-image-o" aria-hidden="true"></i> file-image-o</div>
                <div class="mm_icon" data-icon="fa-file-pdf-o"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> file-pdf-o</div>
                <div class="mm_icon" data-icon="fa-file-powerpoint-o"><i class="fa fa-file-powerpoint-o" aria-hidden="true"></i> file-powerpoint-o</div>
                <div class="mm_icon" data-icon="fa-file-video-o"><i class="fa fa-file-video-o" aria-hidden="true"></i> file-video-o</div>
                <div class="mm_icon" data-icon="fa-file-word-o"><i class="fa fa-file-word-o" aria-hidden="true"></i> file-word-o</div>
                <div class="mm_icon" data-icon="fa-film"><i class="fa fa-film" aria-hidden="true"></i> film</div>
                <div class="mm_icon" data-icon="fa-filter"><i class="fa fa-filter" aria-hidden="true"></i> filter</div>
                <div class="mm_icon" data-icon="fa-fire"><i class="fa fa-fire" aria-hidden="true"></i> fire</div>
                <div class="mm_icon" data-icon="fa-fire-extinguisher"><i class="fa fa-fire-extinguisher" aria-hidden="true"></i> fire-extinguisher</div>
                <div class="mm_icon" data-icon="fa-flag"><i class="fa fa-flag" aria-hidden="true"></i> flag</div>
                <div class="mm_icon" data-icon="fa-flag-checkered"><i class="fa fa-flag-checkered" aria-hidden="true"></i> flag-checkered</div>
                <div class="mm_icon" data-icon="fa-flag-o"><i class="fa fa-flag-o" aria-hidden="true"></i> flag-o</div>
                <div class="mm_icon" data-icon="fa-flask"><i class="fa fa-flask" aria-hidden="true"></i> flask</div>
                <div class="mm_icon" data-icon="fa-folder"><i class="fa fa-folder" aria-hidden="true"></i> folder</div>
                <div class="mm_icon" data-icon="fa-folder-o"><i class="fa fa-folder-o" aria-hidden="true"></i> folder-o</div>
                <div class="mm_icon" data-icon="fa-folder-open"><i class="fa fa-folder-open" aria-hidden="true"></i> folder-open</div>
                <div class="mm_icon" data-icon="fa-folder-open-o"><i class="fa fa-folder-open-o" aria-hidden="true"></i> folder-open-o</div>
                <div class="mm_icon" data-icon="fa-frown-o"><i class="fa fa-frown-o" aria-hidden="true"></i> frown-o</div>
                <div class="mm_icon" data-icon="fa-futbol-o"><i class="fa fa-futbol-o" aria-hidden="true"></i> futbol-o</div>
                <div class="mm_icon" data-icon="fa-gamepad"><i class="fa fa-gamepad" aria-hidden="true"></i> gamepad</div>
                <div class="mm_icon" data-icon="fa-gavel"><i class="fa fa-gavel" aria-hidden="true"></i> gavel</div>
                <div class="mm_icon" data-icon="fa-gift"><i class="fa fa-gift" aria-hidden="true"></i> gift</div>
                <div class="mm_icon" data-icon="fa-glass"><i class="fa fa-glass" aria-hidden="true"></i> glass</div>
                <div class="mm_icon" data-icon="fa-globe"><i class="fa fa-globe" aria-hidden="true"></i> globe</div>
                <div class="mm_icon" data-icon="fa-graduation-cap"><i class="fa fa-graduation-cap" aria-hidden="true"></i> graduation-cap</div>
                <div class="mm_icon" data-icon="fa-hand-lizard-o"><i class="fa fa-hand-lizard-o" aria-hidden="true"></i> hand-lizard-o</div>
                <div class="mm_icon" data-icon="fa-hand-paper-o"><i class="fa fa-hand-paper-o" aria-hidden="true"></i> hand-paper-o</div>
                <div class="mm_icon" data-icon="fa-hand-peace-o"><i class="fa fa-hand-peace-o" aria-hidden="true"></i> hand-peace-o</div>
                <div class="mm_icon" data-icon="fa-hand-pointer-o"><i class="fa fa-hand-pointer-o" aria-hidden="true"></i> hand-pointer-o</div>
                <div class="mm_icon" data-icon="fa-hand-rock-o"><i class="fa fa-hand-rock-o" aria-hidden="true"></i> hand-rock-o</div>
                <div class="mm_icon" data-icon="fa-hand-scissors-o"><i class="fa fa-hand-scissors-o" aria-hidden="true"></i> hand-scissors-o</div>
                <div class="mm_icon" data-icon="fa-hand-spock-o"><i class="fa fa-hand-spock-o" aria-hidden="true"></i> hand-spock-o</div>
                <div class="mm_icon" data-icon="fa-handshake-o"><i class="fa fa-handshake-o" aria-hidden="true"></i> handshake-o</div>
                <div class="mm_icon" data-icon="fa-hashtag"><i class="fa fa-hashtag" aria-hidden="true"></i> hashtag</div>
                <div class="mm_icon" data-icon="fa-hdd-o"><i class="fa fa-hdd-o" aria-hidden="true"></i> hdd-o</div>
                <div class="mm_icon" data-icon="fa-headphones"><i class="fa fa-headphones" aria-hidden="true"></i> headphones</div>
                <div class="mm_icon" data-icon="fa-heart"><i class="fa fa-heart" aria-hidden="true"></i> heart</div>
                <div class="mm_icon" data-icon="fa-heart-o"><i class="fa fa-heart-o" aria-hidden="true"></i> heart-o</div>
                <div class="mm_icon" data-icon="fa-heartbeat"><i class="fa fa-heartbeat" aria-hidden="true"></i> heartbeat</div>
                <div class="mm_icon" data-icon="fa-history"><i class="fa fa-history" aria-hidden="true"></i> history</div>
                <div class="mm_icon" data-icon="fa-home"><i class="fa fa-home" aria-hidden="true"></i> home</div>
                <div class="mm_icon" data-icon="fa-hourglass"><i class="fa fa-hourglass" aria-hidden="true"></i> hourglass</div>
                <div class="mm_icon" data-icon="fa-hourglass-end"><i class="fa fa-hourglass-end" aria-hidden="true"></i> hourglass-end</div>
                <div class="mm_icon" data-icon="fa-hourglass-half"><i class="fa fa-hourglass-half" aria-hidden="true"></i> hourglass-half</div>
                <div class="mm_icon" data-icon="fa-hourglass-o"><i class="fa fa-hourglass-o" aria-hidden="true"></i> hourglass-o</div>
                <div class="mm_icon" data-icon="fa-hourglass-start"><i class="fa fa-hourglass-start" aria-hidden="true"></i> hourglass-start</div>
                <div class="mm_icon" data-icon="fa-i-cursor"><i class="fa fa-i-cursor" aria-hidden="true"></i> i-cursor</div>
                <div class="mm_icon" data-icon="fa-id-badge"><i class="fa fa-id-badge" aria-hidden="true"></i> id-badge</div>
                <div class="mm_icon" data-icon="fa-id-card"><i class="fa fa-id-card" aria-hidden="true"></i> id-card</div>
                <div class="mm_icon" data-icon="fa-id-card-o"><i class="fa fa-id-card-o" aria-hidden="true"></i> id-card-o</div>
                <div class="mm_icon" data-icon="fa-inbox"><i class="fa fa-inbox" aria-hidden="true"></i> inbox</div>
                <div class="mm_icon" data-icon="fa-industry"><i class="fa fa-industry" aria-hidden="true"></i> industry</div>
                <div class="mm_icon" data-icon="fa-info"><i class="fa fa-info" aria-hidden="true"></i> info</div>
                <div class="mm_icon" data-icon="fa-info-circle"><i class="fa fa-info-circle" aria-hidden="true"></i> info-circle</div>
                <div class="mm_icon" data-icon="fa-key"><i class="fa fa-key" aria-hidden="true"></i> key</div>
                <div class="mm_icon" data-icon="fa-keyboard-o"><i class="fa fa-keyboard-o" aria-hidden="true"></i> keyboard-o</div>
                <div class="mm_icon" data-icon="fa-language"><i class="fa fa-language" aria-hidden="true"></i> language</div>
                <div class="mm_icon" data-icon="fa-laptop"><i class="fa fa-laptop" aria-hidden="true"></i> laptop</div>
                <div class="mm_icon" data-icon="fa-leaf"><i class="fa fa-leaf" aria-hidden="true"></i> leaf</div>
                <div class="mm_icon" data-icon="fa-lemon-o"><i class="fa fa-lemon-o" aria-hidden="true"></i> lemon-o</div>
                <div class="mm_icon" data-icon="fa-level-down"><i class="fa fa-level-down" aria-hidden="true"></i> level-down</div>
                <div class="mm_icon" data-icon="fa-level-up"><i class="fa fa-level-up" aria-hidden="true"></i> level-up</div>
                <div class="mm_icon" data-icon="fa-life-ring"><i class="fa fa-life-ring" aria-hidden="true"></i> life-ring</div>
                <div class="mm_icon" data-icon="fa-lightbulb-o"><i class="fa fa-lightbulb-o" aria-hidden="true"></i> lightbulb-o</div>
                <div class="mm_icon" data-icon="fa-line-chart"><i class="fa fa-line-chart" aria-hidden="true"></i> line-chart</div>
                <div class="mm_icon" data-icon="fa-location-arrow"><i class="fa fa-location-arrow" aria-hidden="true"></i> location-arrow</div>
                <div class="mm_icon" data-icon="fa-lock"><i class="fa fa-lock" aria-hidden="true"></i> lock</div>
                <div class="mm_icon" data-icon="fa-low-vision"><i class="fa fa-low-vision" aria-hidden="true"></i> low-vision</div>
                <div class="mm_icon" data-icon="fa-magic"><i class="fa fa-magic" aria-hidden="true"></i> magic</div>
                <div class="mm_icon" data-icon="fa-magnet"><i class="fa fa-magnet" aria-hidden="true"></i> magnet</div>
                <div class="mm_icon" data-icon="fa-male"><i class="fa fa-male" aria-hidden="true"></i> male</div>
                <div class="mm_icon" data-icon="fa-map"><i class="fa fa-map" aria-hidden="true"></i> map</div>
                <div class="mm_icon" data-icon="fa-map-marker"><i class="fa fa-map-marker" aria-hidden="true"></i> map-marker</div>
                <div class="mm_icon" data-icon="fa-map-o"><i class="fa fa-map-o" aria-hidden="true"></i> map-o</div>
                <div class="mm_icon" data-icon="fa-map-pin"><i class="fa fa-map-pin" aria-hidden="true"></i> map-pin</div>
                <div class="mm_icon" data-icon="fa-map-signs"><i class="fa fa-map-signs" aria-hidden="true"></i> map-signs</div>
                <div class="mm_icon" data-icon="fa-meh-o"><i class="fa fa-meh-o" aria-hidden="true"></i> meh-o</div>
                <div class="mm_icon" data-icon="fa-microchip"><i class="fa fa-microchip" aria-hidden="true"></i> microchip</div>
                <div class="mm_icon" data-icon="fa-microphone"><i class="fa fa-microphone" aria-hidden="true"></i> microphone</div>
                <div class="mm_icon" data-icon="fa-microphone-slash"><i class="fa fa-microphone-slash" aria-hidden="true"></i> microphone-slash</div>
                <div class="mm_icon" data-icon="fa-minus"><i class="fa fa-minus" aria-hidden="true"></i> minus</div>
                <div class="mm_icon" data-icon="fa-minus-circle"><i class="fa fa-minus-circle" aria-hidden="true"></i> minus-circle</div>
                <div class="mm_icon" data-icon="fa-minus-square"><i class="fa fa-minus-square" aria-hidden="true"></i> minus-square</div>
                <div class="mm_icon" data-icon="fa-minus-square-o"><i class="fa fa-minus-square-o" aria-hidden="true"></i> minus-square-o</div>
                <div class="mm_icon" data-icon="fa-mobile"><i class="fa fa-mobile" aria-hidden="true"></i> mobile</div>
                <div class="mm_icon" data-icon="fa-money"><i class="fa fa-money" aria-hidden="true"></i> money</div>
                <div class="mm_icon" data-icon="fa-moon-o"><i class="fa fa-moon-o" aria-hidden="true"></i> moon-o</div>
                <div class="mm_icon" data-icon="fa-motorcycle"><i class="fa fa-motorcycle" aria-hidden="true"></i> motorcycle</div>
                <div class="mm_icon" data-icon="fa-mouse-pointer"><i class="fa fa-mouse-pointer" aria-hidden="true"></i> mouse-pointer</div>
                <div class="mm_icon" data-icon="fa-music"><i class="fa fa-music" aria-hidden="true"></i> music</div>
                <div class="mm_icon" data-icon="fa-newspaper-o"><i class="fa fa-newspaper-o" aria-hidden="true"></i> newspaper-o</div>
                <div class="mm_icon" data-icon="fa-object-group"><i class="fa fa-object-group" aria-hidden="true"></i> object-group</div>
                <div class="mm_icon" data-icon="fa-object-ungroup"><i class="fa fa-object-ungroup" aria-hidden="true"></i> object-ungroup</div>
                <div class="mm_icon" data-icon="fa-paint-brush"><i class="fa fa-paint-brush" aria-hidden="true"></i> paint-brush</div>
                <div class="mm_icon" data-icon="fa-paper-plane"><i class="fa fa-paper-plane" aria-hidden="true"></i> paper-plane</div>
                <div class="mm_icon" data-icon="fa-paper-plane-o"><i class="fa fa-paper-plane-o" aria-hidden="true"></i> paper-plane-o</div>
                <div class="mm_icon" data-icon="fa-paw"><i class="fa fa-paw" aria-hidden="true"></i> paw</div>
                <div class="mm_icon" data-icon="fa-pencil"><i class="fa fa-pencil" aria-hidden="true"></i> pencil</div>
                <div class="mm_icon" data-icon="fa-pencil-square"><i class="fa fa-pencil-square" aria-hidden="true"></i> pencil-square</div>
                <div class="mm_icon" data-icon="fa-pencil-square-o"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> pencil-square-o</div>
                <div class="mm_icon" data-icon="fa-percent"><i class="fa fa-percent" aria-hidden="true"></i> percent</div>
                <div class="mm_icon" data-icon="fa-phone"><i class="fa fa-phone" aria-hidden="true"></i> phone</div>
                <div class="mm_icon" data-icon="fa-phone-square"><i class="fa fa-phone-square" aria-hidden="true"></i> phone-square</div>
                <div class="mm_icon" data-icon="fa-picture-o"><i class="fa fa-picture-o" aria-hidden="true"></i> picture-o</div>
                <div class="mm_icon" data-icon="fa-pie-chart"><i class="fa fa-pie-chart" aria-hidden="true"></i> pie-chart</div>
                <div class="mm_icon" data-icon="fa-plane"><i class="fa fa-plane" aria-hidden="true"></i> plane</div>
                <div class="mm_icon" data-icon="fa-plug"><i class="fa fa-plug" aria-hidden="true"></i> plug</div>
                <div class="mm_icon" data-icon="fa-plus"><i class="fa fa-plus" aria-hidden="true"></i> plus</div>
                <div class="mm_icon" data-icon="fa-plus-circle"><i class="fa fa-plus-circle" aria-hidden="true"></i> plus-circle</div>
                <div class="mm_icon" data-icon="fa-plus-square"><i class="fa fa-plus-square" aria-hidden="true"></i> plus-square</div>
                <div class="mm_icon" data-icon="fa-plus-square-o"><i class="fa fa-plus-square-o" aria-hidden="true"></i> plus-square-o</div>
                <div class="mm_icon" data-icon="fa-podcast"><i class="fa fa-podcast" aria-hidden="true"></i> podcast</div>
                <div class="mm_icon" data-icon="fa-power-off"><i class="fa fa-power-off" aria-hidden="true"></i> power-off</div>
                <div class="mm_icon" data-icon="fa-print"><i class="fa fa-print" aria-hidden="true"></i> print</div>
                <div class="mm_icon" data-icon="fa-puzzle-piece"><i class="fa fa-puzzle-piece" aria-hidden="true"></i> puzzle-piece</div>
                <div class="mm_icon" data-icon="fa-qrcode"><i class="fa fa-qrcode" aria-hidden="true"></i> qrcode</div>
                <div class="mm_icon" data-icon="fa-question"><i class="fa fa-question" aria-hidden="true"></i> question</div>
                <div class="mm_icon" data-icon="fa-question-circle"><i class="fa fa-question-circle" aria-hidden="true"></i> question-circle</div>
                <div class="mm_icon" data-icon="fa-question-circle-o"><i class="fa fa-question-circle-o" aria-hidden="true"></i> question-circle-o</div>
                <div class="mm_icon" data-icon="fa-quote-left"><i class="fa fa-quote-left" aria-hidden="true"></i> quote-left</div>
                <div class="mm_icon" data-icon="fa-quote-right"><i class="fa fa-quote-right" aria-hidden="true"></i> quote-right</div>
                <div class="mm_icon" data-icon="fa-random"><i class="fa fa-random" aria-hidden="true"></i> random</div>
                <div class="mm_icon" data-icon="fa-recycle"><i class="fa fa-recycle" aria-hidden="true"></i> recycle</div>
                <div class="mm_icon" data-icon="fa-refresh"><i class="fa fa-refresh" aria-hidden="true"></i> refresh</div>
                <div class="mm_icon" data-icon="fa-registered"><i class="fa fa-registered" aria-hidden="true"></i> registered</div>
                <div class="mm_icon" data-icon="fa-reply"><i class="fa fa-reply" aria-hidden="true"></i> reply</div>
                <div class="mm_icon" data-icon="fa-reply-all"><i class="fa fa-reply-all" aria-hidden="true"></i> reply-all</div>
                <div class="mm_icon" data-icon="fa-retweet"><i class="fa fa-retweet" aria-hidden="true"></i> retweet</div>
                <div class="mm_icon" data-icon="fa-road"><i class="fa fa-road" aria-hidden="true"></i> road</div>
                <div class="mm_icon" data-icon="fa-rocket"><i class="fa fa-rocket" aria-hidden="true"></i> rocket</div>
                <div class="mm_icon" data-icon="fa-rss"><i class="fa fa-rss" aria-hidden="true"></i> rss</div>
                <div class="mm_icon" data-icon="fa-rss-square"><i class="fa fa-rss-square" aria-hidden="true"></i> rss-square</div>
                <div class="mm_icon" data-icon="fa-search"><i class="fa fa-search" aria-hidden="true"></i> search</div>
                <div class="mm_icon" data-icon="fa-search-minus"><i class="fa fa-search-minus" aria-hidden="true"></i> search-minus</div>
                <div class="mm_icon" data-icon="fa-search-plus"><i class="fa fa-search-plus" aria-hidden="true"></i> search-plus</div>
                <div class="mm_icon" data-icon="fa-server"><i class="fa fa-server" aria-hidden="true"></i> server</div>
                <div class="mm_icon" data-icon="fa-share"><i class="fa fa-share" aria-hidden="true"></i> share</div>
                <div class="mm_icon" data-icon="fa-share-alt"><i class="fa fa-share-alt" aria-hidden="true"></i> share-alt</div>
                <div class="mm_icon" data-icon="fa-share-alt-square"><i class="fa fa-share-alt-square" aria-hidden="true"></i> share-alt-square</div>
                <div class="mm_icon" data-icon="fa-share-square"><i class="fa fa-share-square" aria-hidden="true"></i> share-square</div>
                <div class="mm_icon" data-icon="fa-share-square-o"><i class="fa fa-share-square-o" aria-hidden="true"></i> share-square-o</div>
                <div class="mm_icon" data-icon="fa-shield"><i class="fa fa-shield" aria-hidden="true"></i> shield</div>
                <div class="mm_icon" data-icon="fa-ship"><i class="fa fa-ship" aria-hidden="true"></i> ship</div>
                <div class="mm_icon" data-icon="fa-shopping-bag"><i class="fa fa-shopping-bag" aria-hidden="true"></i> shopping-bag</div>
                <div class="mm_icon" data-icon="fa-shopping-basket"><i class="fa fa-shopping-basket" aria-hidden="true"></i> shopping-basket</div>
                <div class="mm_icon" data-icon="fa-shopping-cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i> shopping-cart</div>
                <div class="mm_icon" data-icon="fa-shower"><i class="fa fa-shower" aria-hidden="true"></i> shower</div>
                <div class="mm_icon" data-icon="fa-sign-in"><i class="fa fa-sign-in" aria-hidden="true"></i> sign-in</div>
                <div class="mm_icon" data-icon="fa-sign-language"><i class="fa fa-sign-language" aria-hidden="true"></i> sign-language</div>
                <div class="mm_icon" data-icon="fa-sign-out"><i class="fa fa-sign-out" aria-hidden="true"></i> sign-out</div>
                <div class="mm_icon" data-icon="fa-signal"><i class="fa fa-signal" aria-hidden="true"></i> signal</div>
                <div class="mm_icon" data-icon="fa-sitemap"><i class="fa fa-sitemap" aria-hidden="true"></i> sitemap</div>
                <div class="mm_icon" data-icon="fa-sliders"><i class="fa fa-sliders" aria-hidden="true"></i> sliders</div>
                <div class="mm_icon" data-icon="fa-smile-o"><i class="fa fa-smile-o" aria-hidden="true"></i> smile-o</div>
                <div class="mm_icon" data-icon="fa-snowflake-o"><i class="fa fa-snowflake-o" aria-hidden="true"></i> snowflake-o</div>
                <div class="mm_icon" data-icon="fa-sort"><i class="fa fa-sort" aria-hidden="true"></i> sort</div>
                <div class="mm_icon" data-icon="fa-sort-alpha-asc"><i class="fa fa-sort-alpha-asc" aria-hidden="true"></i> sort-alpha-asc</div>
                <div class="mm_icon" data-icon="fa-sort-alpha-desc"><i class="fa fa-sort-alpha-desc" aria-hidden="true"></i> sort-alpha-desc</div>
                <div class="mm_icon" data-icon="fa-sort-amount-asc"><i class="fa fa-sort-amount-asc" aria-hidden="true"></i> sort-amount-asc</div>
                <div class="mm_icon" data-icon="fa-sort-amount-desc"><i class="fa fa-sort-amount-desc" aria-hidden="true"></i> sort-amount-desc</div>
                <div class="mm_icon" data-icon="fa-sort-asc"><i class="fa fa-sort-asc" aria-hidden="true"></i> sort-asc</div>
                <div class="mm_icon" data-icon="fa-sort-desc"><i class="fa fa-sort-desc" aria-hidden="true"></i> sort-desc</div>
                <div class="mm_icon" data-icon="fa-sort-numeric-asc"><i class="fa fa-sort-numeric-asc" aria-hidden="true"></i> sort-numeric-asc</div>
                <div class="mm_icon" data-icon="fa-sort-numeric-desc"><i class="fa fa-sort-numeric-desc" aria-hidden="true"></i> sort-numeric-desc</div>
                <div class="mm_icon" data-icon="fa-space-shuttle"><i class="fa fa-space-shuttle" aria-hidden="true"></i> space-shuttle</div>
                <div class="mm_icon" data-icon="fa-spinner"><i class="fa fa-spinner" aria-hidden="true"></i> spinner</div>
                <div class="mm_icon" data-icon="fa-spoon"><i class="fa fa-spoon" aria-hidden="true"></i> spoon</div>
                <div class="mm_icon" data-icon="fa-square"><i class="fa fa-square" aria-hidden="true"></i> square</div>
                <div class="mm_icon" data-icon="fa-square-o"><i class="fa fa-square-o" aria-hidden="true"></i> square-o</div>
                <div class="mm_icon" data-icon="fa-star"><i class="fa fa-star" aria-hidden="true"></i> star</div>
                <div class="mm_icon" data-icon="fa-star-half"><i class="fa fa-star-half" aria-hidden="true"></i> star-half</div>
                <div class="mm_icon" data-icon="fa-star-half-o"><i class="fa fa-star-half-o" aria-hidden="true"></i> star-half-o</div>
                <div class="mm_icon" data-icon="fa-star-o"><i class="fa fa-star-o" aria-hidden="true"></i> star-o</div>
                <div class="mm_icon" data-icon="fa-sticky-note"><i class="fa fa-sticky-note" aria-hidden="true"></i> sticky-note</div>
                <div class="mm_icon" data-icon="fa-sticky-note-o"><i class="fa fa-sticky-note-o" aria-hidden="true"></i> sticky-note-o</div>
                <div class="mm_icon" data-icon="fa-street-view"><i class="fa fa-street-view" aria-hidden="true"></i> street-view</div>
                <div class="mm_icon" data-icon="fa-suitcase"><i class="fa fa-suitcase" aria-hidden="true"></i> suitcase</div>
                <div class="mm_icon" data-icon="fa-sun-o"><i class="fa fa-sun-o" aria-hidden="true"></i> sun-o</div>
                <div class="mm_icon" data-icon="fa-tablet"><i class="fa fa-tablet" aria-hidden="true"></i> tablet</div>
                <div class="mm_icon" data-icon="fa-tachometer"><i class="fa fa-tachometer" aria-hidden="true"></i> tachometer</div>
                <div class="mm_icon" data-icon="fa-tag"><i class="fa fa-tag" aria-hidden="true"></i> tag</div>
                <div class="mm_icon" data-icon="fa-tags"><i class="fa fa-tags" aria-hidden="true"></i> tags</div>
                <div class="mm_icon" data-icon="fa-tasks"><i class="fa fa-tasks" aria-hidden="true"></i> tasks</div>
                <div class="mm_icon" data-icon="fa-taxi"><i class="fa fa-taxi" aria-hidden="true"></i> taxi</div>
                <div class="mm_icon" data-icon="fa-television"><i class="fa fa-television" aria-hidden="true"></i> television</div>
                <div class="mm_icon" data-icon="fa-terminal"><i class="fa fa-terminal" aria-hidden="true"></i> terminal</div>
                <div class="mm_icon" data-icon="fa-thermometer-full"><i class="fa fa-thermometer-full" aria-hidden="true"></i> thermometer-full</div>
                <div class="mm_icon" data-icon="fa-thermometer-half"><i class="fa fa-thermometer-half" aria-hidden="true"></i> thermometer-half</div>
                <div class="mm_icon" data-icon="fa-thermometer-quarter"><i class="fa fa-thermometer-quarter" aria-hidden="true"></i> thermometer-quarter</div>
                <div class="mm_icon" data-icon="fa-thermometer-three-quarters"><i class="fa fa-thermometer-three-quarters" aria-hidden="true"></i> thermometer-three-quarters</div>
                <div class="mm_icon" data-icon="fa-thumb-tack"><i class="fa fa-thumb-tack" aria-hidden="true"></i> thumb-tack</div>
                <div class="mm_icon" data-icon="fa-thumbs-down"><i class="fa fa-thumbs-down" aria-hidden="true"></i> thumbs-down</div>
                <div class="mm_icon" data-icon="fa-thumbs-o-down"><i class="fa fa-thumbs-o-down" aria-hidden="true"></i> thumbs-o-down</div>
                <div class="mm_icon" data-icon="fa-thumbs-o-up"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> thumbs-o-up</div>
                <div class="mm_icon" data-icon="fa-thumbs-up"><i class="fa fa-thumbs-up" aria-hidden="true"></i> thumbs-up</div>
                <div class="mm_icon" data-icon="fa-ticket"><i class="fa fa-ticket" aria-hidden="true"></i> ticket</div>
                <div class="mm_icon" data-icon="fa-times"><i class="fa fa-times" aria-hidden="true"></i> times</div>
                <div class="mm_icon" data-icon="fa-times-circle"><i class="fa fa-times-circle" aria-hidden="true"></i> times-circle</div>
                <div class="mm_icon" data-icon="fa-times-circle-o"><i class="fa fa-times-circle-o" aria-hidden="true"></i> times-circle-o</div>
                <div class="mm_icon" data-icon="fa-tint"><i class="fa fa-tint" aria-hidden="true"></i> tint</div>
                <div class="mm_icon" data-icon="fa-toggle-off"><i class="fa fa-toggle-off" aria-hidden="true"></i> toggle-off</div>
                <div class="mm_icon" data-icon="fa-toggle-on"><i class="fa fa-toggle-on" aria-hidden="true"></i> toggle-on</div>
                <div class="mm_icon" data-icon="fa-trademark"><i class="fa fa-trademark" aria-hidden="true"></i> trademark</div>
                <div class="mm_icon" data-icon="fa-trash"><i class="fa fa-trash" aria-hidden="true"></i> trash</div>
                <div class="mm_icon" data-icon="fa-trash-o"><i class="fa fa-trash-o" aria-hidden="true"></i> trash-o</div>
                <div class="mm_icon" data-icon="fa-tree"><i class="fa fa-tree" aria-hidden="true"></i> tree</div>
                <div class="mm_icon" data-icon="fa-trophy"><i class="fa fa-trophy" aria-hidden="true"></i> trophy</div>
                <div class="mm_icon" data-icon="fa-truck"><i class="fa fa-truck" aria-hidden="true"></i> truck</div>
                <div class="mm_icon" data-icon="fa-tty"><i class="fa fa-tty" aria-hidden="true"></i> tty</div>
                <div class="mm_icon" data-icon="fa-umbrella"><i class="fa fa-umbrella" aria-hidden="true"></i> umbrella</div>
                <div class="mm_icon" data-icon="fa-universal-access"><i class="fa fa-universal-access" aria-hidden="true"></i> universal-access</div>
                <div class="mm_icon" data-icon="fa-university"><i class="fa fa-university" aria-hidden="true"></i> university</div>
                <div class="mm_icon" data-icon="fa-unlock"><i class="fa fa-unlock" aria-hidden="true"></i> unlock</div>
                <div class="mm_icon" data-icon="fa-unlock-alt"><i class="fa fa-unlock-alt" aria-hidden="true"></i> unlock-alt</div>
                <div class="mm_icon" data-icon="fa-upload"><i class="fa fa-upload" aria-hidden="true"></i> upload</div>
                <div class="mm_icon" data-icon="fa-user"><i class="fa fa-user" aria-hidden="true"></i> user</div>
                <div class="mm_icon" data-icon="fa-user-circle"><i class="fa fa-user-circle" aria-hidden="true"></i> user-circle</div>
                <div class="mm_icon" data-icon="fa-user-circle-o"><i class="fa fa-user-circle-o" aria-hidden="true"></i> user-circle-o</div>
                <div class="mm_icon" data-icon="fa-user-o"><i class="fa fa-user-o" aria-hidden="true"></i> user-o</div>
                <div class="mm_icon" data-icon="fa-user-plus"><i class="fa fa-user-plus" aria-hidden="true"></i> user-plus</div>
                <div class="mm_icon" data-icon="fa-user-secret"><i class="fa fa-user-secret" aria-hidden="true"></i> user-secret</div>
                <div class="mm_icon" data-icon="fa-user-times"><i class="fa fa-user-times" aria-hidden="true"></i> user-times</div>
                <div class="mm_icon" data-icon="fa-users"><i class="fa fa-users" aria-hidden="true"></i> users</div>
                <div class="mm_icon" data-icon="fa-video-camera"><i class="fa fa-video-camera" aria-hidden="true"></i> video-camera</div>
                <div class="mm_icon" data-icon="fa-volume-control-phone"><i class="fa fa-volume-control-phone" aria-hidden="true"></i> volume-control-phone</div>
                <div class="mm_icon" data-icon="fa-volume-down"><i class="fa fa-volume-down" aria-hidden="true"></i> volume-down</div>
                <div class="mm_icon" data-icon="fa-volume-off"><i class="fa fa-volume-off" aria-hidden="true"></i> volume-off</div>
                <div class="mm_icon" data-icon="fa-volume-up"><i class="fa fa-volume-up" aria-hidden="true"></i> volume-up</div>
                <div class="mm_icon" data-icon="fa-wheelchair"><i class="fa fa-wheelchair" aria-hidden="true"></i> wheelchair</div>
                <div class="mm_icon" data-icon="fa-wheelchair-alt"><i class="fa fa-wheelchair-alt" aria-hidden="true"></i> wheelchair-alt</div>
                <div class="mm_icon" data-icon="fa-wifi"><i class="fa fa-wifi" aria-hidden="true"></i> wifi</div>
                <div class="mm_icon" data-icon="fa-window-close"><i class="fa fa-window-close" aria-hidden="true"></i> window-close</div>
                <div class="mm_icon" data-icon="fa-window-close-o"><i class="fa fa-window-close-o" aria-hidden="true"></i> window-close-o</div>
                <div class="mm_icon" data-icon="fa-window-maximize"><i class="fa fa-window-maximize" aria-hidden="true"></i> window-maximize</div>
                <div class="mm_icon" data-icon="fa-window-minimize"><i class="fa fa-window-minimize" aria-hidden="true"></i> window-minimize</div>
                <div class="mm_icon" data-icon="fa-window-restore"><i class="fa fa-window-restore" aria-hidden="true"></i> window-restore</div>
                <div class="mm_icon" data-icon="fa-wrench"><i class="fa fa-wrench" aria-hidden="true"></i> wrench</div>
            </div>
        </div>
    </div>
</div>